services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mystore
      MYSQL_ROOT_PASSWORD: securepassword
    ports:
      - "3306:3306"
    volumes:
      - mystore_db_data:/var/lib/mysql
      - ./sql/mystore.sql:/docker-entrypoint-initdb.d/01_mystore.sql
      - ./sql/update_phase2.sql:/docker-entrypoint-initdb.d/02_update_phase2.sql
      - ./sql/update_phase3.sql:/docker-entrypoint-initdb.d/03_update_phase3.sql

volumes:
  mystore_app_site:
  mystore_db_data:
